### ISSUE TITLE
pygobject3: fix the build

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#346]
On https://hub.docker.com/r/nsls2/debian-with-miniconda/ it fails with missing `py3cairo`:
```
./configure: line 13250: ./libtool: No such file or directory
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.38.0... yes (version 2.51.4)
checking for FFI... yes
checking for GIO... yes
checking for GI... yes
checking for CAIRO... yes
checking for PYCAIRO... no
configure: error: Package requirements (py3cairo >= 1.10.0
        ) were not met:

No package 'py3cairo' found
......................................
<Skipping huge amount of debug prints>
......................................
configure: exit 1
+ exit 1
Traceback (most recent call last):
  File "/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/conda/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/conda/lib/python3.6/site-packages/conda_build/build.py", line 1771, in build_tree
    notest=notest,
  File "/conda/lib/python3.6/site-packages/conda_build/build.py", line 1121, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/conda/lib/python3.6/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/conda/lib/python3.6/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/conda/conda-bld/pygobject3_1526453195996/work/conda_build.sh']' returned non-zero exit status 1.
```
Note: I may have played with updating the GLIB to version higher than 2.38.0. Originally the error was (if I remember correctly):
```
root@1b17278f5d01:/lightsource2-recipes/recipes-tag/pygobject3-3.12.0/pygobject# python setup.py install
running install
running bdist_egg
running egg_info
writing PyGObject.egg-info/PKG-INFO
writing dependency_links to PyGObject.egg-info/dependency_links.txt
writing requirements to PyGObject.egg-info/requires.txt
writing top-level names to PyGObject.egg-info/top_level.txt
reading manifest file 'PyGObject.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'PyGObject.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Requested 'glib-2.0 >= 2.38.0' but version of GLib is 2.32.4
Command '('pkg-config', '--print-errors', '--exists', 'glib-2.0 >= 2.38.0')' returned non-zero exit status 1.
```

When I tried to build py3cairo, it fails with:
```
err: gcc: error: unrecognized command line option ‘-fstack-protector-strong’
gcc: error: unrecognized command line option ‘-fno-plt’

from /conda/conda-bld/py3cairo_1526453580583/work: Test does not build: Traceback (most recent call last):
  File "/conda/conda-bld/py3cairo_1526453580583/work/.waf3-1.8.16-62b1bd1a26843637845309e604a98bca/waflib/Configure.py", line 334, in run_build
    bld.compile()
  File "/conda/conda-bld/py3cairo_1526453580583/work/.waf3-1.8.16-62b1bd1a26843637845309e604a98bca/waflib/Build.py", line 185, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed (exit status 1):
        {task 140337214178528: c test.c -> test.c.1.o}
['/usr/bin/gcc', '-I/conda/conda-bld/py3cairo_1526453580583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/cairo', '-march=nocona', '-mtune=haswell', '-ftree-vectorize', '-fPIC', '-fstack-protector-strong', '-fno-plt', '-fdebug-prefix-map=/conda/conda-bld/py3cairo_1526453580583/work=/usr/local/src/conda/py3cairo-1.10.0', '-fdebug-prefix-map=/conda/conda-bld/py3cairo_1526453580583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol=/usr/local/src/conda-prefix', '-fuse-linker-plugin', '-ffat-lto-objects', '-flto-partition=none', '-flto', '-fwrapv', '-I/conda/conda-bld/py3cairo_1526453580583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/python3.6m', '-DPYTHONDIR="/conda/conda-bld/py3cairo_1526453580583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages"', '-DPYTHONARCHDIR="/conda/conda-bld/py3cairo_1526453580583/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages"', '-DHAVE_PYEMBED=1', '-DNDEBUG', '../test.c', '-c', '-o', '/conda/conda-bld/py3cairo_1526453580583/work/build_directory/.conf_check_e5ffacd4be07fbc37d9247b6713ac146/testbuild/test.c.1.o']

Could not build a python embedded interpreter
from /conda/conda-bld/py3cairo_1526453580583/work: The configuration failed
```

We may consider switching to https://gitlab.gnome.org/GNOME/pygobject/tags/3.29.2 or newer version, but an attempt to build it failed as well. Need to investigate.

**Comment by mrakitin** [comment]
FYI: I used this link to update glib: https://ubuntuforums.org/showthread.php?t=1607632
```
sudo apt-get install libperl-dev
sudo apt-get install libgtk2.0-dev
```
which didn't solve the problem, but may be useful for future reference.

**Comment by mrakitin** [comment]
It was resolved via https://github.com/NSLS-II/lightsource2-recipes/pull/472.
