### ISSUE TITLE
Problem with using pyFAI

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/lightsource2-recipes#647]
Observed with @awalter-bnl and @gfreychet during the SMI deployment 19-2.
```py
(/opt/conda_envs/analysis-2019-2.0-smi) xf12id@xf12id-ws1:~/.ipython/profile_collection/startup$ ipython
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pyFAI                                                                                                                           
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-3965c5b1fb28> in <module>
----> 1 import pyFAI

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/pyFAI/__init__.py in <module>
     55     raise RuntimeError("pyFAI required a python version >= 2.6, now we are running: %s" % sys.version)
     56 
---> 57 from .utils import decorators
     58 
     59 

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/pyFAI/utils/__init__.py in <module>
     44 import threading
     45 sem = threading.Semaphore()  # global lock for image processing initialization
---> 46 import fabio
     47 
     48 from .._version import calc_hexversion

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/__init__.py in <module>
     46 from . import fabioimage
     47 factory = fabioimage.FabioImage.factory
---> 48 from . import openimage
     49 from .fabioutils import COMPRESSORS, jump_filename, FilenameObject, \
     50         previous_filename, next_filename, deconstruct_filename, \

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/openimage.py in <module>
     60 from . import fit2dspreadsheetimage
     61 from . import kcdimage
---> 62 from . import cbfimage
     63 from . import xsdimage
     64 from . import binaryimage

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/cbfimage.py in <module>
     54 from .fabioimage import FabioImage
     55 from .compression import compByteOffset, decByteOffset, md5sum, six
---> 56 from .ext._cif import split_tokens
     57 
     58 

__init__.pxd in init fabio.ext._cif()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

In [2]:                                                                                                                                        

In [2]: from pyFAI import AzimuthalIntegrator                                                                                                  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9e840c902602> in <module>
----> 1 from pyFAI import AzimuthalIntegrator

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/pyFAI/__init__.py in <module>
     55     raise RuntimeError("pyFAI required a python version >= 2.6, now we are running: %s" % sys.version)
     56 
---> 57 from .utils import decorators
     58 
     59 

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/pyFAI/utils/__init__.py in <module>
     44 import threading
     45 sem = threading.Semaphore()  # global lock for image processing initialization
---> 46 import fabio
     47 
     48 from .._version import calc_hexversion

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/__init__.py in <module>
     46 from . import fabioimage
     47 factory = fabioimage.FabioImage.factory
---> 48 from . import openimage
     49 from .fabioutils import COMPRESSORS, jump_filename, FilenameObject, \
     50         previous_filename, next_filename, deconstruct_filename, \

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/openimage.py in <module>
     60 from . import fit2dspreadsheetimage
     61 from . import kcdimage
---> 62 from . import cbfimage
     63 from . import xsdimage
     64 from . import binaryimage

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/cbfimage.py in <module>
     54 from .fabioimage import FabioImage
     55 from .compression import compByteOffset, decByteOffset, md5sum, six
---> 56 from .ext._cif import split_tokens
     57 
     58 

/opt/conda_envs/analysis-2019-2.0-smi/lib/python3.6/site-packages/fabio/ext/_cif.cpython-36m-x86_64-linux-gnu.so in init fabio.ext._cif()

AttributeError: type object 'fabio.ext._cif.array' has no attribute '__reduce_cython__'

In [3]:                                                                                                                                        
```

**Comment by mrakitin** [comment]
@CJ-Wright, are you observing the same issue?

**Comment by CJ-Wright** [comment]
Not exactly but that is because I hit it through skbeam, but I expect they are from the same source (the need for a fabio rebuild)
```python
File "/opt/conda_envs/collection-2019-2.0-xpd/bin/save_server", line 8, in <module>
    from xpdan.startup.save_server import run_main
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/startup/save_server.py", line 4, in <module>
    from xpdan.callbacks import SAVER_MAP
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/xpdan/callbacks.py", line 7, in <module>
    from skbeam.io.fit2d import fit2d_save
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/skbeam/io/fit2d.py", line 4, in <module>
    from fabio.fit2dmaskimage import Fit2dMaskImage
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/fabio/__init__.py", line 48, in <module>
    from . import openimage
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/fabio/openimage.py", line 62, in <module>
    from . import cbfimage
  File "/opt/conda_envs/collection-2019-2.0-xpd/lib/python3.6/site-packages/fabio/cbfimage.py", line 56, in <module>
    from .ext._cif import split_tokens
  File "__init__.pxd", line 918, in init fabio.ext._cif
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject```

**Comment by mrakitin** [comment]
Last time it was touched was https://github.com/NSLS-II/lightsource2-recipes/pull/508. The only major thing which changed since then (Jan 14, 2019) was patching the metadata on our server. Maybe it caused picking a wrong dependency, or something like that. Any thoughts? Can it be reproduced within a Docker container https://hub.docker.com/r/nsls2/debian-with-miniconda/tags/?

**Comment by CJ-Wright** [comment]
I think the issue is not pyfai but fabio. Fabio has C/C++ bindings and has bindings to numpy. If any of those moved between the most recent fabio build and what is getting shipped in the current environments then that could cause trouble.

**Comment by mrakitin** [comment]
It makes sense. I touched fabio last time while making it buildable for Mac: https://github.com/NSLS-II/lightsource2-recipes/pull/576. I think it also caused some warning for `_tifffile` with the new envs 2019-2.0. Any ideas how to resolve it?

**Comment by ke-zhang-rd** [comment]
close by #656
